### ISSUE TITLE
how to pack javafx with springboot into exe.

### ISSUE THREAD

**Issue by koy-tome** [roskenet/springboot-javafx-support#71]
I tried to use exe4j but it failed. Is there any other way? Thank you.

**Comment by roskenet** [comment]
Unfortunately I don't use and have any Windows installation at all and I cannot provide any help here.
To find a solution for your problem it would be good to check first, if it's a) JavaFX, b) Spring, c) the support-lib or d) any combination of it.
I would try to build some tiny-playground projects for each of those possibilities.

**Comment by mtbadi39** [comment]
Hi;
[launch4j-maven-plugin](https://github.com/lukaszlenart/launch4j-maven-plugin) is a perfect choice, we use it for a while.
It is a cross-platform tool for wrapping any Java Application distributed as jar in lightweight Windows native executables.
This [simple-pom.zip](https://github.com/roskenet/springboot-javafx-support/files/1984386/simple-pom.zip) my help.

**Edit :** 

- not tested with spring-boot (because of [spring-boot-loader](https://github.com/spring-projects/spring-boot#spring-boot-loader))
- [spring-boot-daemon](https://github.com/snicoll-scratches/spring-boot-daemon) : Showcase of deploying a Spring Boot application as a Windows Service

**Comment by roskenet** [comment]
Thanks @mtbadi39 
Since this issue does not directly address this project, I'll close it for now.
