### ISSUE TITLE
Load css in the Scene

### ISSUE THREAD

**Issue by TioCoding** [roskenet/springboot-javafx-support#8]
Hi, how can I do to load only once the css to the General Scene (AbstractJavaFxApplicationSupport) ?, instead of declaring it in all my views @FXMLView (css = {"..."}). Since my intention is that all views use the same css. Thank you so much :)

**Comment by roskenet** [comment]
Thanks for your comment.
As far as I understand you want to set one css for all scenes globally. Since this is not supported from JavaFX itself I'm not sure yet, if this is the "JavaFX-way" to go - I need to think about it.
But you should be able to add your "global css" to all your views via the FXMLView-annotation (or with SceneBuilder directly).
Do you think of a global property (in the application.yaml) setting a css?

**Comment by TioCoding** [comment]
Of course, my intention is to be able to declare a css file that is recognized by all views (.fxml). For example, before using this framework I made it with this method when declaring the scene:
```
Scene scene = new Scene(parent);
scene.getStylesheets().add(Main.class.getResource("/css/roboto.css").toExternalForm());
scene.getStylesheets().add(Main.class.getResource("/css/style.css").toExternalForm());
```

And all views automatically recognize the .css without the need to explicitly declare it in all views. It would be interesting to be able to configure that property from the application.yml, would be very flexible and easy to maintain.

**Comment by roskenet** [comment]
O.k. I'll take care of that.

**Comment by roskenet** [comment]
Done with 1.3.19
Added a global javafx.css property. Be aware that the path is absolute to the classpath. To avoid ambiguity it needs to have a trailing slash: When global.css is under /src/main/resources/ in the maven project it will be:
javafx.css=/global.css 
for the compiled and packaged app. (Will add more styling examples in the docu).

**Comment by roskenet** [comment]
Done with 1.3.19
